# basic options
title: MacsApps
author: Michael Clark
email: mikec7592@gmail.com
description: A collection of ongoing projects
github_username:  mikec7592
linkedin: www.linkedin.com/in/mikec7592/

# Build settings
markdown: kramdown
theme: minima
